quarkus.oidc.application-type=web_app
quarkus.oidc.authentication.pkce-required=true
quarkus.oidc.authentication.redirect-path=/oidc/callback
quarkus.oidc.authentication.restore-path-after-redirect=true
quarkus.oidc.authentication.user-info-required=true
quarkus.oidc.logout.path=/logout
quarkus.oidc.logout.post-logout-path=/
